# Generated by Django 3.0.10 on 2020-11-03 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.TextField(default='The description of a hub', max_length=500, verbose_name="Hub's Description"),
        ),
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(default='Hub', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_tag', inverse_match=True)], verbose_name="Hub's Name"),
        ),
    ]
