# Generated by Django 3.0.10 on 2020-11-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0002_auto_20201103_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hub',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hub', to=settings.AUTH_USER_MODEL),
        ),
    ]
