# Generated by Django 3.0.10 on 2020-11-03 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0003_auto_20201103_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='member',
            field=models.ManyToManyField(related_name='joined_hub', to=settings.AUTH_USER_MODEL),
        ),
    ]
