# Generated by Django 3.0.10 on 2020-11-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0004_auto_20201103_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hub',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='joined_hub', to=settings.AUTH_USER_MODEL),
        ),
    ]
