# Generated by Django 3.0.10 on 2020-11-07 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0005_auto_20201104_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='slug',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.TextField(max_length=500, verbose_name="Hub's Description"),
        ),
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_tag', inverse_match=True)], verbose_name="Hub's Name"),
        ),
    ]
