# Generated by Django 3.0.10 on 2020-11-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0007_auto_20201107_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='short_description',
            field=models.CharField(blank=True, max_length=64, verbose_name="Hub's Short Description"),
        ),
    ]
