# Generated by Django 3.0.10 on 2020-11-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_auto_20201103_1926'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Publicity'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is the content of a post', max_length=5000, verbose_name="Post's body"),
        ),
        migrations.AlterField(
            model_name='post',
            name='hub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='This is the title of a post', max_length=128, verbose_name="Post's Title"),
        ),
    ]
