# Generated by Django 3.0.10 on 2020-11-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0002_auto_20201103_1926'),
        ('posts', '0002_auto_20201103_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='hubs.Hub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
