# Generated by Django 3.0.10 on 2020-11-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_auto_20201103_2215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20201103_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default="My awesome post's content", max_length=5000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains_post', to='hubs.Hub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default="My awesome post's title", max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
