# Generated by Django 3.0.10 on 2020-11-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0007_auto_20201107_2105'),
        ('posts', '0005_auto_20201104_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains_post', to='hubs.Hub'),
        ),
    ]
